"""
Django settings for jobcorner project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*q$p#=rf75761td*^iyrn%acj2k+o_iz(-kbi39xhrrta352@d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
AUTH_USER_MODEL = 'accounts.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.flatpages',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',

    'widget_tweaks',
    'crispy_forms',
    'extra_views',
    'markdown_deux',
    'pagedown',
    'django_filters',
    'taggit',

    "pinax.likes",
    "pinax.messages",
    "pinax.testimonials",
    "pinax.blog",
    "pinax.images",
    "pinax.notifications",

    'accounts',
    'category',
    'company',
    'country',
    'homepage',
    'job',
    'location',
    'reviews',
    'resume',

    'actstream',

]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobcorner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobcorner.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

LOGOUT_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL = 'home'
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'amazingace00@gmail.com'
EMAIL_HOST_PASSWORD = 'tungsten1'
EMAIL_PORT = 587

# LOGIN_REDIRECT_URL = 'accounts:profile'
PINAX_LIKES_LIKABLE_MODELS = {
    "accounts.User": {
        "like_text_on": "unlike",
        "css_class_on": "fa-heart btn std-btn btn-sm btn-warning",
        "like_text_off": "like",
        "css_class_off": "fa-heart-o btn std-btn btn-sm btn-filled",
        "allowed": lambda user, obj: True
    },
    "job.Job": {
        "like_text_on": "unlike",
        "css_class_on": "fa-heart btn std-btn btn-sm btn-warning",
        "like_text_off": "like",
        "css_class_off": "fa-heart-o btn std-btn btn-sm btn-filled",
        "allowed": lambda user, obj: True
    },
    "reviews.Review": {
        "like_text_on": "unlike",
        "css_class_on": "fa-heart btn std-btn btn-sm btn-warning",
        "like_text_off": "like",
        "css_class_off": "fa-heart-o btn std-btn btn-sm btn-filled",
        "allowed": lambda user, obj: True
    },
}

AUTHENTICATION_BACKENDS = [
    # other backends
    "pinax.likes.auth_backends.CanLikeBackend",
]

ACTSTREAM_SETTINGS = {
    'MANAGER': 'accounts.managers.MyActionManager',
    'FETCH_RELATIONS': True,
    'USE_PREFETCH': True,
    'USE_JSONFIELD': True,
    'GFK_FETCH_DEPTH': 1,
}

CRISPY_TEMPLATE_PACK = 'bootstrap4'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_cdn")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media_cdn")
