# Generated by Django 2.1.7 on 2019-03-27 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(help_text='qualification, responsibilities,  requirements,  benefits, Experience')),
                ('application_info', models.TextField(help_text="What's the best way to apply for this job?")),
                ('work_hours', models.CharField(blank=True, max_length=80)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remote', models.BooleanField(default=False, help_text='Select if this job allows 100% remote working')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.Location')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
